# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_price_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='volume',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
