# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_auto_20170607_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
            ],
            options={
                'db_table': 'pricedate',
            },
        ),
        migrations.AlterField(
            model_name='price',
            name='diesel',
            field=models.FloatField(blank=True, null=True, verbose_name='\u0414\u0438\u0437\u0435\u043b\u044c'),
        ),
        migrations.AlterField(
            model_name='price',
            name='petrol_92',
            field=models.FloatField(blank=True, null=True, verbose_name='\u0411\u0435\u043d\u0437\u0438\u043d 92'),
        ),
        migrations.AlterField(
            model_name='price',
            name='petrol_95',
            field=models.FloatField(blank=True, null=True, verbose_name='\u0411\u0435\u043d\u0437\u0438\u043d 95'),
        ),
        migrations.AlterField(
            model_name='price',
            name='volume',
            field=models.CharField(blank=True, max_length=30, verbose_name='\u041e\u0431\u044a\u0435\u043c'),
        ),
    ]
