# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0005_auto_20170607_0205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceDate',
        ),
        migrations.AddField(
            model_name='price',
            name='price_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430'),
        ),
    ]
