# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0007_auto_20170607_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_date',
            field=models.CharField(blank=True, default=True, max_length=20, verbose_name='\u0414\u0430\u0442\u0430'),
        ),
    ]
