# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0008_auto_20170609_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceLadoga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petrol95_ladoga', models.FloatField(blank=True, null=True, verbose_name='\u041b\u0430\u0434\u043e\u0433\u0430 \u0411\u0435\u043d\u0437\u0438\u043d 95')),
                ('petrol92_ladoga', models.FloatField(blank=True, null=True, verbose_name='\u041b\u0430\u0434\u043e\u0433\u0430 \u0411\u0435\u043d\u0437\u0438\u043d 92')),
                ('diesel_ladoga', models.FloatField(blank=True, null=True, verbose_name='\u041b\u0430\u0434\u043e\u0433\u0430 \u0414\u0438\u0437\u0435\u043b\u044c')),
                ('pricedate_ladoga', models.DateField(verbose_name='\u0414\u0430\u0442\u0430')),
            ],
            options={
                'db_table': 'price_ladoga',
                'verbose_name': '\u041f\u0440\u0430\u0439\u0441 \u041b\u0430\u0434\u043e\u0433\u0430',
                'verbose_name_plural': '\u041f\u0440\u0430\u0439\u0441-\u043b\u0438\u0441\u0442\u044b \u041b\u0430\u0434\u043e\u0433\u0430',
            },
        ),
        migrations.CreateModel(
            name='PriceNekrasova',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petrol95_nekrasova', models.FloatField(blank=True, null=True, verbose_name='\u041d\u0435\u043a\u0440\u0430\u0441\u043e\u0432\u0430 \u0411\u0435\u043d\u0437\u0438\u043d 95')),
                ('petrol92_nekrasova', models.FloatField(blank=True, null=True, verbose_name='\u041d\u0435\u043a\u0440\u0430\u0441\u043e\u0432\u0430 \u0411\u0435\u043d\u0437\u0438\u043d 92')),
                ('diesel_nekrasova', models.FloatField(blank=True, null=True, verbose_name='\u041d\u0435\u043a\u0440\u0430\u0441\u043e\u0432\u0430 \u0414\u0438\u0437\u0435\u043b\u044c')),
                ('pricedate_nekrasova', models.DateField(verbose_name='\u0414\u0430\u0442\u0430')),
            ],
            options={
                'db_table': 'price_nekrasova',
                'verbose_name': '\u041f\u0440\u0430\u0439\u0441 \u041d\u0435\u043a\u0440\u0430\u0441\u043e\u0432\u0430',
                'verbose_name_plural': '\u041f\u0440\u0430\u0439\u0441-\u043b\u0438\u0441\u0442\u044b \u041d\u0435\u043a\u0440\u0430\u0441\u043e\u0432\u0430',
            },
        ),
        migrations.CreateModel(
            name='PricePupish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petrol95_pupish', models.FloatField(blank=True, null=True, verbose_name='\u041f\u0443\u043f\u044b\u0448\u0435\u0432\u043e \u0411\u0435\u043d\u0437\u0438\u043d 95')),
                ('petrol92_pupish', models.FloatField(blank=True, null=True, verbose_name='\u041f\u0443\u043f\u044b\u0448\u0435\u0432\u043e \u0411\u0435\u043d\u0437\u0438\u043d 92')),
                ('diesel_pupish', models.FloatField(blank=True, null=True, verbose_name='\u041f\u0443\u043f\u044b\u0448\u0435\u0432\u043e \u0414\u0438\u0437\u0435\u043b\u044c')),
                ('pricedate_pupish', models.DateField(verbose_name='\u0414\u0430\u0442\u0430')),
            ],
            options={
                'db_table': 'price_pupish',
                'verbose_name': '\u041f\u0440\u0430\u0439\u0441 \u041b\u0430\u0434\u043e\u0433\u0430',
                'verbose_name_plural': '\u041f\u0440\u0430\u0439\u0441-\u043b\u0438\u0441\u0442\u044b \u041f\u0443\u043f\u044b\u0448\u0435\u0432\u043e',
            },
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': '\u041e\u043f\u0442\u043e\u0432\u044b\u0435 \u0446\u0435\u043d\u044b', 'verbose_name_plural': '\u041e\u043f\u0442\u043e\u0432\u044b\u0435 \u043f\u0440\u0430\u0439\u0441-\u043b\u0438\u0441\u0442\u044b'},
        ),
    ]
