# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect_firstname', models.CharField(max_length=15, verbose_name='\u0418\u043c\u044f')),
                ('connect_lastname', models.CharField(max_length=15, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('connect_mail', models.EmailField(max_length=120, verbose_name='E-mail')),
                ('connect_phonenumber', models.IntegerField(verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
                ('connect_text', models.TextField(verbose_name='\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435')),
            ],
            options={
                'db_table': 'connect',
            },
        ),
    ]
