# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_auto_20170529_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='connect_mail',
            field=models.EmailField(max_length=120, verbose_name='E-mail'),
        ),
    ]
