# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 21:00
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0006_auto_20170529_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts_info', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b')),
                ('contacts_details', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u0420\u0435\u043a\u0432\u0438\u0437\u0438\u0442\u044b')),
            ],
            options={
                'db_table': 'contacts',
                'verbose_name': '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b \u0438 \u0440\u0435\u043a\u0432\u0438\u0437\u0438\u0442\u044b',
                'verbose_name_plural': '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b \u0438 \u0440\u0435\u043a\u0432\u0438\u0437\u0438\u0442\u044b',
            },
        ),
    ]
